---

# curl https://api.github.com/repos/sharkdp/bat/releases/latest | jq .assets[12].browser_download_url
- name: install bat
  apt:
    deb: https://github.com/sharkdp/bat/releases/download/v0.18.1/bat_0.18.1_amd64.deb
  become: true

- name: install neovim nightly
  block:
    - name: Clone repo
      git:
        repo: 'https://github.com/neovim/neovim.git'
        dest: '/home/nequo/git/neovim'
      register: nvimrepo
    - name: Make
      make:
        chdir: '/home/nequo/git/neovim'
        params:
          CMAKE_BUILD_TYPE: Release
      when: nvimrepo.changed
      become: true
    - name: Make Install
      make:
        chdir: '/home/nequo/git/neovim'
        target: install
      when: nvimrepo.changed
      become: true

- name: install ergodox wally
  block:
    - name: Install dependencies
      package:
        name: libusb-dev
        state: present
      become: true

    - name: Set Udev rule
      copy:
        src:
        dest: /etc/udev/rules.d/50-wally.rules
        content: |
          # Teensy rules for the Ergodox EZ
          ATTRS{idVendor}=="16c0", ATTRS{idProduct}=="04[789B]?", ENV{ID_MM_DEVICE_IGNORE}="1"
          ATTRS{idVendor}=="16c0", ATTRS{idProduct}=="04[789A]?", ENV{MTP_NO_PROBE}="1"
          SUBSYSTEMS=="usb", ATTRS{idVendor}=="16c0", ATTRS{idProduct}=="04[789ABCD]?", MODE:="0666"
          KERNEL=="ttyACM*", ATTRS{idVendor}=="16c0", ATTRS{idProduct}=="04[789B]?", MODE:="0666"

          # STM32 rules for the Moonlander and Planck EZ
          SUBSYSTEMS=="usb", ATTRS{idVendor}=="0483", ATTRS{idProduct}=="df11", \
              MODE:="0666", \
              SYMLINK+="stm32_dfu"
      become: true

    - name: Create plugdev group
      group:
        name: plugdev
        state: present

    - name: Add user to plugdev
      user:
        name: "{{ ansible_user_id }}"
        groups: plugdev
        append: yes
      become: yes

    - name: install wally
      get_url:
        url: https://configure.ergodox-ez.com/wally/linux
        dest: /usr/local/bin/wally
        mode: '775'
      become: true
